In [1]:
import numpy as np
import pandas as pd

# New Section

In [2]:
from google.colab import files
up=files.upload()

Saving institute project.xlsx to institute project.xlsx

In [3]:
df=pd.read_excel('institute project.xlsx')
df

,NAME OF THE STUDENT,QUALIFICATION,NAME OF COLLEGE,YEAR OF GRADUATION,STREAM OF GRADUATION,COURSE \n,EXPECTED DURATION OF COURSE,MONTH OF JOINING\n\n,FEE PAID FOR THE COURSE,SATISFACTION LEVEL OF FEE STRUCTURE,STATISFACTION LEVEL OF TRAINERS QUALITY,ON WHAT BASES YOU WANT TO REFER YOUR FRIEND,CHANCES OF GETTING PLACEMENTS,HOW DID YOU KNOW ABOUT THIS INSTITUTE,WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION
0,Rakesh,BTECH,Kg Reddy college of engineering and technology,2026,CSE,Python full stack,6 Months,2026-01-01,INCUBATION,5,4,TRANIER QUALITY,3.0,College placement,Nothing
1,Lingamgari Charan Teja,BTECH,Aar Mahaveer Engineering College,2026,CSE,Python full stack,4 Months,2026-01-01,INCUBATION,1,5,TRANIER QUALITY,2.0,GOOGLE SEARCHED,NaN
2,Sharuk Shaik,BTECH,Kakatiya University,2026,CSE,Data Science,3 Months,2026-01-01,INCUBATION,4,4,PLACEMENTS,4.0,College placement,NaN
3,C Krithik Reddy,BTECH,Mahaveer Institute of Science and Technology,2026,CSE,Java full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,5.0,College placement,NaN
4,Shubham Kumar Roy,BTECH,Mahaveer institute of science and technology,2026,CSE,Data Science,3 Months,2026-01-01,INCUBATION,3,5,TRANIER QUALITY,3.0,GOOGLE SEARCHED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Riya,OTHERS,Lenora college of engineering,2026,CSE (AI&ML),Data Science,6 Months,2025-12-01,18000 TO 23000,3,4,TRANIER QUALITY,2.0,FRIEND REFERENCE,Good 👍
226,Kottapally Sreya,BTECH,Aurora's Technology and Research Institute,2026,CSE (AI&ML),Python full stack,4 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,Teaching should a little bit faster I think it...
227,Vanaparthi Anjali,BTECH,Vignan Institute of technology and science,2026,CSE,Data Analytics,6 Months,2026-01-01,18000 TO 23000,2,4,FREE ADD ON COURSE FOR YOU,4.0,FRIEND REFERENCE,Expecting More Teaching Time and Minimal stren...
228,T.Tejaswi,BTECH,Aurora's technological and research institute,2026,CSE,Python full stack,5 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,seperate classes should provide for each and ...
229,Vijaya Sri,BTECH,Anurag Engineering College,2026,CSE,Python full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,3.0,ADVERTISEMENT,Placements

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 15 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   NAME OF THE  STUDENT                                            230 non-null    object
 1   QUALIFICATION                                                   230 non-null    object
 2   NAME OF COLLEGE                                                 230 non-null    object
 3   YEAR OF GRADUATION                                              230 non-null    int64
 4   STREAM OF GRADUATION                                            230 non-null    object
 5   COURSE
                                                        230 non-null    object
 6   EXPECTED DURATION OF COURSE                                     230 non-null    object
 7   MONTH OF JOINING

                                              230 non-null    datetime64[ns]
 8   FEE PAID FOR THE COURSE                                         230 non-null    object
 9   SATISFACTION LEVEL OF FEE STRUCTURE                             230 non-null    int64
 10  STATISFACTION LEVEL OF TRAINERS QUALITY                         230 non-null    int64
 11  ON WHAT BASES YOU WANT TO REFER YOUR FRIEND                     227 non-null    object
 12  CHANCES OF GETTING PLACEMENTS                                   222 non-null    float64
 13  HOW DID YOU KNOW ABOUT THIS INSTITUTE                           230 non-null    object
 14  WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION  130 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(10)
memory usage: 27.1+ KB

In [5]:
df.describe()

,YEAR OF GRADUATION,MONTH OF JOINING\n\n,SATISFACTION LEVEL OF FEE STRUCTURE,STATISFACTION LEVEL OF TRAINERS QUALITY,CHANCES OF GETTING PLACEMENTS
count,230.000000,230,230.000000,230.000000,222.000000
mean,2025.860870,2025-12-14 12:12:31.304347904,4.078261,4.400000,3.635135
min,2022.000000,2025-11-01 00:00:00,1.000000,1.000000,1.000000
25%,2026.000000,2025-12-01 00:00:00,3.000000,4.000000,3.000000
50%,2026.000000,2025-12-01 00:00:00,5.000000,5.000000,4.000000
75%,2026.000000,2026-01-01 00:00:00,5.000000,5.000000,4.000000
max,2026.000000,2026-02-01 00:00:00,5.000000,5.000000,5.000000
std,0.474447,NaN,1.208759,0.941985,0.987354

In [6]:
df.duplicated().count()

np.int64(230)

In [7]:
df['WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION'] = \
df['WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION'].fillna('Nothing')
df

,NAME OF THE STUDENT,QUALIFICATION,NAME OF COLLEGE,YEAR OF GRADUATION,STREAM OF GRADUATION,COURSE \n,EXPECTED DURATION OF COURSE,MONTH OF JOINING\n\n,FEE PAID FOR THE COURSE,SATISFACTION LEVEL OF FEE STRUCTURE,STATISFACTION LEVEL OF TRAINERS QUALITY,ON WHAT BASES YOU WANT TO REFER YOUR FRIEND,CHANCES OF GETTING PLACEMENTS,HOW DID YOU KNOW ABOUT THIS INSTITUTE,WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION
0,Rakesh,BTECH,Kg Reddy college of engineering and technology,2026,CSE,Python full stack,6 Months,2026-01-01,INCUBATION,5,4,TRANIER QUALITY,3.0,College placement,Nothing
1,Lingamgari Charan Teja,BTECH,Aar Mahaveer Engineering College,2026,CSE,Python full stack,4 Months,2026-01-01,INCUBATION,1,5,TRANIER QUALITY,2.0,GOOGLE SEARCHED,Nothing
2,Sharuk Shaik,BTECH,Kakatiya University,2026,CSE,Data Science,3 Months,2026-01-01,INCUBATION,4,4,PLACEMENTS,4.0,College placement,Nothing
3,C Krithik Reddy,BTECH,Mahaveer Institute of Science and Technology,2026,CSE,Java full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,5.0,College placement,Nothing
4,Shubham Kumar Roy,BTECH,Mahaveer institute of science and technology,2026,CSE,Data Science,3 Months,2026-01-01,INCUBATION,3,5,TRANIER QUALITY,3.0,GOOGLE SEARCHED,Nothing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Riya,OTHERS,Lenora college of engineering,2026,CSE (AI&ML),Data Science,6 Months,2025-12-01,18000 TO 23000,3,4,TRANIER QUALITY,2.0,FRIEND REFERENCE,Good 👍
226,Kottapally Sreya,BTECH,Aurora's Technology and Research Institute,2026,CSE (AI&ML),Python full stack,4 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,Teaching should a little bit faster I think it...
227,Vanaparthi Anjali,BTECH,Vignan Institute of technology and science,2026,CSE,Data Analytics,6 Months,2026-01-01,18000 TO 23000,2,4,FREE ADD ON COURSE FOR YOU,4.0,FRIEND REFERENCE,Expecting More Teaching Time and Minimal stren...
228,T.Tejaswi,BTECH,Aurora's technological and research institute,2026,CSE,Python full stack,5 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,seperate classes should provide for each and ...
229,Vijaya Sri,BTECH,Anurag Engineering College,2026,CSE,Python full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,3.0,ADVERTISEMENT,Placements

In [8]:
df['NAME OF COLLEGE'] = (df['NAME OF COLLEGE'].str.lower())
df['COURSE \n'] = (df['COURSE \n'].str.lower())
df['WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION']=(df['WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION'].str.lower())
df.head()

,NAME OF THE STUDENT,QUALIFICATION,NAME OF COLLEGE,YEAR OF GRADUATION,STREAM OF GRADUATION,COURSE \n,EXPECTED DURATION OF COURSE,MONTH OF JOINING\n\n,FEE PAID FOR THE COURSE,SATISFACTION LEVEL OF FEE STRUCTURE,STATISFACTION LEVEL OF TRAINERS QUALITY,ON WHAT BASES YOU WANT TO REFER YOUR FRIEND,CHANCES OF GETTING PLACEMENTS,HOW DID YOU KNOW ABOUT THIS INSTITUTE,WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION
0,Rakesh,BTECH,kg reddy college of engineering and technology,2026,CSE,python full stack,6 Months,2026-01-01,INCUBATION,5,4,TRANIER QUALITY,3.0,College placement,nothing
1,Lingamgari Charan Teja,BTECH,aar mahaveer engineering college,2026,CSE,python full stack,4 Months,2026-01-01,INCUBATION,1,5,TRANIER QUALITY,2.0,GOOGLE SEARCHED,nothing
2,Sharuk Shaik,BTECH,kakatiya university,2026,CSE,data science,3 Months,2026-01-01,INCUBATION,4,4,PLACEMENTS,4.0,College placement,nothing
3,C Krithik Reddy,BTECH,mahaveer institute of science and technology,2026,CSE,java full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,5.0,College placement,nothing
4,Shubham Kumar Roy,BTECH,mahaveer institute of science and technology,2026,CSE,data science,3 Months,2026-01-01,INCUBATION,3,5,TRANIER QUALITY,3.0,GOOGLE SEARCHED,nothing

In [9]:
df['CHANCES OF GETTING PLACEMENTS'].mode()

0    4.0
Name: CHANCES OF GETTING PLACEMENTS, dtype: float64

In [10]:
df['CHANCES OF GETTING PLACEMENTS'].fillna(4.0,inplace=True)
df

/tmp/ipython-input-2499102606.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CHANCES OF GETTING PLACEMENTS'].fillna(4.0,inplace=True)

,NAME OF THE STUDENT,QUALIFICATION,NAME OF COLLEGE,YEAR OF GRADUATION,STREAM OF GRADUATION,COURSE \n,EXPECTED DURATION OF COURSE,MONTH OF JOINING\n\n,FEE PAID FOR THE COURSE,SATISFACTION LEVEL OF FEE STRUCTURE,STATISFACTION LEVEL OF TRAINERS QUALITY,ON WHAT BASES YOU WANT TO REFER YOUR FRIEND,CHANCES OF GETTING PLACEMENTS,HOW DID YOU KNOW ABOUT THIS INSTITUTE,WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION
0,Rakesh,BTECH,kg reddy college of engineering and technology,2026,CSE,python full stack,6 Months,2026-01-01,INCUBATION,5,4,TRANIER QUALITY,3.0,College placement,nothing
1,Lingamgari Charan Teja,BTECH,aar mahaveer engineering college,2026,CSE,python full stack,4 Months,2026-01-01,INCUBATION,1,5,TRANIER QUALITY,2.0,GOOGLE SEARCHED,nothing
2,Sharuk Shaik,BTECH,kakatiya university,2026,CSE,data science,3 Months,2026-01-01,INCUBATION,4,4,PLACEMENTS,4.0,College placement,nothing
3,C Krithik Reddy,BTECH,mahaveer institute of science and technology,2026,CSE,java full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,5.0,College placement,nothing
4,Shubham Kumar Roy,BTECH,mahaveer institute of science and technology,2026,CSE,data science,3 Months,2026-01-01,INCUBATION,3,5,TRANIER QUALITY,3.0,GOOGLE SEARCHED,nothing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Riya,OTHERS,lenora college of engineering,2026,CSE (AI&ML),data science,6 Months,2025-12-01,18000 TO 23000,3,4,TRANIER QUALITY,2.0,FRIEND REFERENCE,good 👍
226,Kottapally Sreya,BTECH,aurora's technology and research institute,2026,CSE (AI&ML),python full stack,4 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,teaching should a little bit faster i think it...
227,Vanaparthi Anjali,BTECH,vignan institute of technology and science,2026,CSE,data analytics,6 Months,2026-01-01,18000 TO 23000,2,4,FREE ADD ON COURSE FOR YOU,4.0,FRIEND REFERENCE,expecting more teaching time and minimal stren...
228,T.Tejaswi,BTECH,aurora's technological and research institute,2026,CSE,python full stack,5 Months,2026-01-01,18000 TO 23000,4,5,TRANIER QUALITY,3.0,FRIEND REFERENCE,seperate classes should provide for each and ...
229,Vijaya Sri,BTECH,anurag engineering college,2026,CSE,python full stack,4 Months,2026-01-01,INCUBATION,5,5,TRANIER QUALITY,3.0,ADVERTISEMENT,placements

In [11]:
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 227 entries, 0 to 229
Data columns (total 15 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   NAME OF THE  STUDENT                                            227 non-null    object
 1   QUALIFICATION                                                   227 non-null    object
 2   NAME OF COLLEGE                                                 227 non-null    object
 3   YEAR OF GRADUATION                                              227 non-null    int64
 4   STREAM OF GRADUATION                                            227 non-null    object
 5   COURSE
                                                        227 non-null    object
 6   EXPECTED DURATION OF COURSE                                     227 non-null    object
 7   MONTH OF JOINING

                                              227 non-null    datetime64[ns]
 8   FEE PAID FOR THE COURSE                                         227 non-null    object
 9   SATISFACTION LEVEL OF FEE STRUCTURE                             227 non-null    int64
 10  STATISFACTION LEVEL OF TRAINERS QUALITY                         227 non-null    int64
 11  ON WHAT BASES YOU WANT TO REFER YOUR FRIEND                     227 non-null    object
 12  CHANCES OF GETTING PLACEMENTS                                   227 non-null    float64
 13  HOW DID YOU KNOW ABOUT THIS INSTITUTE                           227 non-null    object
 14  WHAT SHOULD BE IMPROVED IN INSTITUTE FOR STUDENTS SATISFACTION  227 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(10)
memory usage: 28.4+ KB

In [12]:
df['STATISFACTION LEVEL OF TRAINERS QUALITY'].mean()

np.float64(4.392070484581498)

In [13]:
df['SATISFACTION LEVEL OF FEE STRUCTURE'].mean()

np.float64(4.070484581497797)

In [14]:
df['CHANCES OF GETTING PLACEMENTS'].mean()

np.float64(3.647577092511013)

In [15]:

df.groupby('COURSE \n').size()

COURSE \n
data analytics                            38
data science                              20
java full stack                           52
python full atack                          1
python full stack                         78
python full stack                          3
python full stack with data analyst        1
python full stack with data analytics      1
python full stock                          1
python with data science                   1
software testing                          31
dtype: int64

In [16]:
df['COURSE \n'] = ( df['COURSE \n'] .str.strip() .str.lower()
    .str.replace('python full atack', ' python full stack')
    .str.replace('python full stock', 'python full stack')
    .str.replace('python full stack with data analyst', 'python full stack with data analytics')
     .str.replace('python full stack', 'python full stack')
)
df.groupby('COURSE \n').size()

COURSE \n
 python full stack                        1
data analytics                           38
data science                             20
java full stack                          52
python full stack                        82
python full stack with data analytics     2
python with data science                  1
software testing                         31
dtype: int64

In [17]:
df['EXPECTED DURATION OF COURSE'].mode()

0    3 Months
Name: EXPECTED DURATION OF COURSE, dtype: object

In [18]:
df.groupby('HOW DID YOU KNOW ABOUT THIS INSTITUTE').size()

HOW DID YOU KNOW ABOUT THIS INSTITUTE
ADVERTISEMENT                  8
College placement            116
College placement              1
FRIEND REFERENCE              76
From College Authorities       1
GOOGLE SEARCHED                7
In our placement               1
Incubation                     1
SOCIAL MEDIA                  16
dtype: int64

In [20]:
df.groupby('YEAR OF GRADUATION').size()

YEAR OF GRADUATION
2022      2
2025     23
2026    202
dtype: int64

In [21]:
#df.to_excel('instituteproject_out.xlsx',index=False)
#from google.colab import files
#files.download("instituteproject_out.xlsx")